### ISSUE TITLE
Resizing of Game Board

### ISSUE THREAD

**Issue by 4E6F** [claudiu-sava/BattleShip#37] opened 2024-01-26 20:31 UTC
Objective: This feature  enabling users to customize the size of the game board to accommodate varying preferences and matrice sizes

- [x] #112
- [x] #113
- [x] #114

**Comment by claudiu-sava** [comment] 2024-01-26 21:11
@4E6F This might be a duplicate of #8

**Closed** 2024-02-03 13:44 UTC
Labels: feature
